_target_: src.models.module.BodyHeightModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.resnet.ResNet
  block:
    _target_: src.models.components.resnet.BasicBlock
    # _target_: src.models.components.resnet.BottlenetckBlock
  layers: [2, 2, 2, 2]
  num_classes: 1
  use_senet: true
  ratio: 16

compile: false
