_target_: src.models.module.BodyHeightModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 10

net:
  _target_: src.models.components.resnet.ResNet
  use_bottleneck_block: true
  layers: [2, 2, 2, 2]
  num_classes: 1
  use_senet: true
  ratio: 16

compile: false
